package com.rickie.dbsdk.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CargoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cargo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public CargoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookingIdIsNull() {
            addCriterion("BOOKING_ID is null");
            return (Criteria) this;
        }

        public Criteria andBookingIdIsNotNull() {
            addCriterion("BOOKING_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBookingIdEqualTo(String value) {
            addCriterion("BOOKING_ID =", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdNotEqualTo(String value) {
            addCriterion("BOOKING_ID <>", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdGreaterThan(String value) {
            addCriterion("BOOKING_ID >", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdGreaterThanOrEqualTo(String value) {
            addCriterion("BOOKING_ID >=", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdLessThan(String value) {
            addCriterion("BOOKING_ID <", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdLessThanOrEqualTo(String value) {
            addCriterion("BOOKING_ID <=", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdLike(String value) {
            addCriterion("BOOKING_ID like", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdNotLike(String value) {
            addCriterion("BOOKING_ID not like", value, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdIn(List<String> values) {
            addCriterion("BOOKING_ID in", values, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdNotIn(List<String> values) {
            addCriterion("BOOKING_ID not in", values, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdBetween(String value1, String value2) {
            addCriterion("BOOKING_ID between", value1, value2, "bookingId");
            return (Criteria) this;
        }

        public Criteria andBookingIdNotBetween(String value1, String value2) {
            addCriterion("BOOKING_ID not between", value1, value2, "bookingId");
            return (Criteria) this;
        }

        public Criteria andTransportStatusIsNull() {
            addCriterion("TRANSPORT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTransportStatusIsNotNull() {
            addCriterion("TRANSPORT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTransportStatusEqualTo(String value) {
            addCriterion("TRANSPORT_STATUS =", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusNotEqualTo(String value) {
            addCriterion("TRANSPORT_STATUS <>", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusGreaterThan(String value) {
            addCriterion("TRANSPORT_STATUS >", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSPORT_STATUS >=", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusLessThan(String value) {
            addCriterion("TRANSPORT_STATUS <", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusLessThanOrEqualTo(String value) {
            addCriterion("TRANSPORT_STATUS <=", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusLike(String value) {
            addCriterion("TRANSPORT_STATUS like", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusNotLike(String value) {
            addCriterion("TRANSPORT_STATUS not like", value, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusIn(List<String> values) {
            addCriterion("TRANSPORT_STATUS in", values, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusNotIn(List<String> values) {
            addCriterion("TRANSPORT_STATUS not in", values, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusBetween(String value1, String value2) {
            addCriterion("TRANSPORT_STATUS between", value1, value2, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andTransportStatusNotBetween(String value1, String value2) {
            addCriterion("TRANSPORT_STATUS not between", value1, value2, "transportStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusIsNull() {
            addCriterion("ROUTING_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusIsNotNull() {
            addCriterion("ROUTING_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusEqualTo(String value) {
            addCriterion("ROUTING_STATUS =", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusNotEqualTo(String value) {
            addCriterion("ROUTING_STATUS <>", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusGreaterThan(String value) {
            addCriterion("ROUTING_STATUS >", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ROUTING_STATUS >=", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusLessThan(String value) {
            addCriterion("ROUTING_STATUS <", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusLessThanOrEqualTo(String value) {
            addCriterion("ROUTING_STATUS <=", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusLike(String value) {
            addCriterion("ROUTING_STATUS like", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusNotLike(String value) {
            addCriterion("ROUTING_STATUS not like", value, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusIn(List<String> values) {
            addCriterion("ROUTING_STATUS in", values, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusNotIn(List<String> values) {
            addCriterion("ROUTING_STATUS not in", values, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusBetween(String value1, String value2) {
            addCriterion("ROUTING_STATUS between", value1, value2, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andRoutingStatusNotBetween(String value1, String value2) {
            addCriterion("ROUTING_STATUS not between", value1, value2, "routingStatus");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdIsNull() {
            addCriterion("spec_origin_id is null");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdIsNotNull() {
            addCriterion("spec_origin_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdEqualTo(String value) {
            addCriterion("spec_origin_id =", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdNotEqualTo(String value) {
            addCriterion("spec_origin_id <>", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdGreaterThan(String value) {
            addCriterion("spec_origin_id >", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdGreaterThanOrEqualTo(String value) {
            addCriterion("spec_origin_id >=", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdLessThan(String value) {
            addCriterion("spec_origin_id <", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdLessThanOrEqualTo(String value) {
            addCriterion("spec_origin_id <=", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdLike(String value) {
            addCriterion("spec_origin_id like", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdNotLike(String value) {
            addCriterion("spec_origin_id not like", value, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdIn(List<String> values) {
            addCriterion("spec_origin_id in", values, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdNotIn(List<String> values) {
            addCriterion("spec_origin_id not in", values, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdBetween(String value1, String value2) {
            addCriterion("spec_origin_id between", value1, value2, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecOriginIdNotBetween(String value1, String value2) {
            addCriterion("spec_origin_id not between", value1, value2, "specOriginId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdIsNull() {
            addCriterion("spec_destination_id is null");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdIsNotNull() {
            addCriterion("spec_destination_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdEqualTo(String value) {
            addCriterion("spec_destination_id =", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdNotEqualTo(String value) {
            addCriterion("spec_destination_id <>", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdGreaterThan(String value) {
            addCriterion("spec_destination_id >", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdGreaterThanOrEqualTo(String value) {
            addCriterion("spec_destination_id >=", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdLessThan(String value) {
            addCriterion("spec_destination_id <", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdLessThanOrEqualTo(String value) {
            addCriterion("spec_destination_id <=", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdLike(String value) {
            addCriterion("spec_destination_id like", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdNotLike(String value) {
            addCriterion("spec_destination_id not like", value, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdIn(List<String> values) {
            addCriterion("spec_destination_id in", values, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdNotIn(List<String> values) {
            addCriterion("spec_destination_id not in", values, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdBetween(String value1, String value2) {
            addCriterion("spec_destination_id between", value1, value2, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecDestinationIdNotBetween(String value1, String value2) {
            addCriterion("spec_destination_id not between", value1, value2, "specDestinationId");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineIsNull() {
            addCriterion("SPEC_ARRIVAL_DEADLINE is null");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineIsNotNull() {
            addCriterion("SPEC_ARRIVAL_DEADLINE is not null");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineEqualTo(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE =", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineNotEqualTo(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE <>", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineGreaterThan(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE >", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE >=", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineLessThan(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE <", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE <=", value, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineIn(List<Date> values) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE in", values, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineNotIn(List<Date> values) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE not in", values, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE between", value1, value2, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andSpecArrivalDeadlineNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SPEC_ARRIVAL_DEADLINE not between", value1, value2, "specArrivalDeadline");
            return (Criteria) this;
        }

        public Criteria andOriginIdIsNull() {
            addCriterion("origin_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginIdIsNotNull() {
            addCriterion("origin_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginIdEqualTo(String value) {
            addCriterion("origin_id =", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotEqualTo(String value) {
            addCriterion("origin_id <>", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdGreaterThan(String value) {
            addCriterion("origin_id >", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdGreaterThanOrEqualTo(String value) {
            addCriterion("origin_id >=", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdLessThan(String value) {
            addCriterion("origin_id <", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdLessThanOrEqualTo(String value) {
            addCriterion("origin_id <=", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdLike(String value) {
            addCriterion("origin_id like", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotLike(String value) {
            addCriterion("origin_id not like", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdIn(List<String> values) {
            addCriterion("origin_id in", values, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotIn(List<String> values) {
            addCriterion("origin_id not in", values, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdBetween(String value1, String value2) {
            addCriterion("origin_id between", value1, value2, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotBetween(String value1, String value2) {
            addCriterion("origin_id not between", value1, value2, "originId");
            return (Criteria) this;
        }

        public Criteria andBookingAmountIsNull() {
            addCriterion("BOOKING_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBookingAmountIsNotNull() {
            addCriterion("BOOKING_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBookingAmountEqualTo(Integer value) {
            addCriterion("BOOKING_AMOUNT =", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountNotEqualTo(Integer value) {
            addCriterion("BOOKING_AMOUNT <>", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountGreaterThan(Integer value) {
            addCriterion("BOOKING_AMOUNT >", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("BOOKING_AMOUNT >=", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountLessThan(Integer value) {
            addCriterion("BOOKING_AMOUNT <", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountLessThanOrEqualTo(Integer value) {
            addCriterion("BOOKING_AMOUNT <=", value, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountIn(List<Integer> values) {
            addCriterion("BOOKING_AMOUNT in", values, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountNotIn(List<Integer> values) {
            addCriterion("BOOKING_AMOUNT not in", values, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountBetween(Integer value1, Integer value2) {
            addCriterion("BOOKING_AMOUNT between", value1, value2, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andBookingAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("BOOKING_AMOUNT not between", value1, value2, "bookingAmount");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdIsNull() {
            addCriterion("handling_event_id is null");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdIsNotNull() {
            addCriterion("handling_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdEqualTo(Integer value) {
            addCriterion("handling_event_id =", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdNotEqualTo(Integer value) {
            addCriterion("handling_event_id <>", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdGreaterThan(Integer value) {
            addCriterion("handling_event_id >", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("handling_event_id >=", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdLessThan(Integer value) {
            addCriterion("handling_event_id <", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("handling_event_id <=", value, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdIn(List<Integer> values) {
            addCriterion("handling_event_id in", values, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdNotIn(List<Integer> values) {
            addCriterion("handling_event_id not in", values, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdBetween(Integer value1, Integer value2) {
            addCriterion("handling_event_id between", value1, value2, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andHandlingEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("handling_event_id not between", value1, value2, "handlingEventId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdIsNull() {
            addCriterion("next_expected_location_id is null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdIsNotNull() {
            addCriterion("next_expected_location_id is not null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdEqualTo(String value) {
            addCriterion("next_expected_location_id =", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdNotEqualTo(String value) {
            addCriterion("next_expected_location_id <>", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdGreaterThan(String value) {
            addCriterion("next_expected_location_id >", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdGreaterThanOrEqualTo(String value) {
            addCriterion("next_expected_location_id >=", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdLessThan(String value) {
            addCriterion("next_expected_location_id <", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdLessThanOrEqualTo(String value) {
            addCriterion("next_expected_location_id <=", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdLike(String value) {
            addCriterion("next_expected_location_id like", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdNotLike(String value) {
            addCriterion("next_expected_location_id not like", value, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdIn(List<String> values) {
            addCriterion("next_expected_location_id in", values, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdNotIn(List<String> values) {
            addCriterion("next_expected_location_id not in", values, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdBetween(String value1, String value2) {
            addCriterion("next_expected_location_id between", value1, value2, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedLocationIdNotBetween(String value1, String value2) {
            addCriterion("next_expected_location_id not between", value1, value2, "nextExpectedLocationId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeIsNull() {
            addCriterion("next_expected_handling_event_type is null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeIsNotNull() {
            addCriterion("next_expected_handling_event_type is not null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeEqualTo(String value) {
            addCriterion("next_expected_handling_event_type =", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeNotEqualTo(String value) {
            addCriterion("next_expected_handling_event_type <>", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeGreaterThan(String value) {
            addCriterion("next_expected_handling_event_type >", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("next_expected_handling_event_type >=", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeLessThan(String value) {
            addCriterion("next_expected_handling_event_type <", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeLessThanOrEqualTo(String value) {
            addCriterion("next_expected_handling_event_type <=", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeLike(String value) {
            addCriterion("next_expected_handling_event_type like", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeNotLike(String value) {
            addCriterion("next_expected_handling_event_type not like", value, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeIn(List<String> values) {
            addCriterion("next_expected_handling_event_type in", values, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeNotIn(List<String> values) {
            addCriterion("next_expected_handling_event_type not in", values, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeBetween(String value1, String value2) {
            addCriterion("next_expected_handling_event_type between", value1, value2, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedHandlingEventTypeNotBetween(String value1, String value2) {
            addCriterion("next_expected_handling_event_type not between", value1, value2, "nextExpectedHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdIsNull() {
            addCriterion("next_expected_voyage_id is null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdIsNotNull() {
            addCriterion("next_expected_voyage_id is not null");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdEqualTo(String value) {
            addCriterion("next_expected_voyage_id =", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdNotEqualTo(String value) {
            addCriterion("next_expected_voyage_id <>", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdGreaterThan(String value) {
            addCriterion("next_expected_voyage_id >", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdGreaterThanOrEqualTo(String value) {
            addCriterion("next_expected_voyage_id >=", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdLessThan(String value) {
            addCriterion("next_expected_voyage_id <", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdLessThanOrEqualTo(String value) {
            addCriterion("next_expected_voyage_id <=", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdLike(String value) {
            addCriterion("next_expected_voyage_id like", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdNotLike(String value) {
            addCriterion("next_expected_voyage_id not like", value, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdIn(List<String> values) {
            addCriterion("next_expected_voyage_id in", values, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdNotIn(List<String> values) {
            addCriterion("next_expected_voyage_id not in", values, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdBetween(String value1, String value2) {
            addCriterion("next_expected_voyage_id between", value1, value2, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andNextExpectedVoyageIdNotBetween(String value1, String value2) {
            addCriterion("next_expected_voyage_id not between", value1, value2, "nextExpectedVoyageId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdIsNull() {
            addCriterion("last_known_location_id is null");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdIsNotNull() {
            addCriterion("last_known_location_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdEqualTo(String value) {
            addCriterion("last_known_location_id =", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdNotEqualTo(String value) {
            addCriterion("last_known_location_id <>", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdGreaterThan(String value) {
            addCriterion("last_known_location_id >", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_known_location_id >=", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdLessThan(String value) {
            addCriterion("last_known_location_id <", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdLessThanOrEqualTo(String value) {
            addCriterion("last_known_location_id <=", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdLike(String value) {
            addCriterion("last_known_location_id like", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdNotLike(String value) {
            addCriterion("last_known_location_id not like", value, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdIn(List<String> values) {
            addCriterion("last_known_location_id in", values, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdNotIn(List<String> values) {
            addCriterion("last_known_location_id not in", values, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdBetween(String value1, String value2) {
            addCriterion("last_known_location_id between", value1, value2, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andLastKnownLocationIdNotBetween(String value1, String value2) {
            addCriterion("last_known_location_id not between", value1, value2, "lastKnownLocationId");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberIsNull() {
            addCriterion("current_voyage_number is null");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberIsNotNull() {
            addCriterion("current_voyage_number is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberEqualTo(String value) {
            addCriterion("current_voyage_number =", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberNotEqualTo(String value) {
            addCriterion("current_voyage_number <>", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberGreaterThan(String value) {
            addCriterion("current_voyage_number >", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberGreaterThanOrEqualTo(String value) {
            addCriterion("current_voyage_number >=", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberLessThan(String value) {
            addCriterion("current_voyage_number <", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberLessThanOrEqualTo(String value) {
            addCriterion("current_voyage_number <=", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberLike(String value) {
            addCriterion("current_voyage_number like", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberNotLike(String value) {
            addCriterion("current_voyage_number not like", value, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberIn(List<String> values) {
            addCriterion("current_voyage_number in", values, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberNotIn(List<String> values) {
            addCriterion("current_voyage_number not in", values, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberBetween(String value1, String value2) {
            addCriterion("current_voyage_number between", value1, value2, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentVoyageNumberNotBetween(String value1, String value2) {
            addCriterion("current_voyage_number not between", value1, value2, "currentVoyageNumber");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdIsNull() {
            addCriterion("last_handling_event_id is null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdIsNotNull() {
            addCriterion("last_handling_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdEqualTo(Integer value) {
            addCriterion("last_handling_event_id =", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdNotEqualTo(Integer value) {
            addCriterion("last_handling_event_id <>", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdGreaterThan(Integer value) {
            addCriterion("last_handling_event_id >", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_handling_event_id >=", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdLessThan(Integer value) {
            addCriterion("last_handling_event_id <", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("last_handling_event_id <=", value, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdIn(List<Integer> values) {
            addCriterion("last_handling_event_id in", values, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdNotIn(List<Integer> values) {
            addCriterion("last_handling_event_id not in", values, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdBetween(Integer value1, Integer value2) {
            addCriterion("last_handling_event_id between", value1, value2, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("last_handling_event_id not between", value1, value2, "lastHandlingEventId");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeIsNull() {
            addCriterion("last_handling_event_type is null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeIsNotNull() {
            addCriterion("last_handling_event_type is not null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeEqualTo(String value) {
            addCriterion("last_handling_event_type =", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeNotEqualTo(String value) {
            addCriterion("last_handling_event_type <>", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeGreaterThan(String value) {
            addCriterion("last_handling_event_type >", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("last_handling_event_type >=", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeLessThan(String value) {
            addCriterion("last_handling_event_type <", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeLessThanOrEqualTo(String value) {
            addCriterion("last_handling_event_type <=", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeLike(String value) {
            addCriterion("last_handling_event_type like", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeNotLike(String value) {
            addCriterion("last_handling_event_type not like", value, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeIn(List<String> values) {
            addCriterion("last_handling_event_type in", values, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeNotIn(List<String> values) {
            addCriterion("last_handling_event_type not in", values, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeBetween(String value1, String value2) {
            addCriterion("last_handling_event_type between", value1, value2, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventTypeNotBetween(String value1, String value2) {
            addCriterion("last_handling_event_type not between", value1, value2, "lastHandlingEventType");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationIsNull() {
            addCriterion("last_handling_event_location is null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationIsNotNull() {
            addCriterion("last_handling_event_location is not null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationEqualTo(String value) {
            addCriterion("last_handling_event_location =", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationNotEqualTo(String value) {
            addCriterion("last_handling_event_location <>", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationGreaterThan(String value) {
            addCriterion("last_handling_event_location >", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationGreaterThanOrEqualTo(String value) {
            addCriterion("last_handling_event_location >=", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationLessThan(String value) {
            addCriterion("last_handling_event_location <", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationLessThanOrEqualTo(String value) {
            addCriterion("last_handling_event_location <=", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationLike(String value) {
            addCriterion("last_handling_event_location like", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationNotLike(String value) {
            addCriterion("last_handling_event_location not like", value, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationIn(List<String> values) {
            addCriterion("last_handling_event_location in", values, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationNotIn(List<String> values) {
            addCriterion("last_handling_event_location not in", values, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationBetween(String value1, String value2) {
            addCriterion("last_handling_event_location between", value1, value2, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventLocationNotBetween(String value1, String value2) {
            addCriterion("last_handling_event_location not between", value1, value2, "lastHandlingEventLocation");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageIsNull() {
            addCriterion("last_handling_event_voyage is null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageIsNotNull() {
            addCriterion("last_handling_event_voyage is not null");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageEqualTo(String value) {
            addCriterion("last_handling_event_voyage =", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageNotEqualTo(String value) {
            addCriterion("last_handling_event_voyage <>", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageGreaterThan(String value) {
            addCriterion("last_handling_event_voyage >", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageGreaterThanOrEqualTo(String value) {
            addCriterion("last_handling_event_voyage >=", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageLessThan(String value) {
            addCriterion("last_handling_event_voyage <", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageLessThanOrEqualTo(String value) {
            addCriterion("last_handling_event_voyage <=", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageLike(String value) {
            addCriterion("last_handling_event_voyage like", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageNotLike(String value) {
            addCriterion("last_handling_event_voyage not like", value, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageIn(List<String> values) {
            addCriterion("last_handling_event_voyage in", values, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageNotIn(List<String> values) {
            addCriterion("last_handling_event_voyage not in", values, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageBetween(String value1, String value2) {
            addCriterion("last_handling_event_voyage between", value1, value2, "lastHandlingEventVoyage");
            return (Criteria) this;
        }

        public Criteria andLastHandlingEventVoyageNotBetween(String value1, String value2) {
            addCriterion("last_handling_event_voyage not between", value1, value2, "lastHandlingEventVoyage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cargo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}