package com.rickie.dbsdk.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LegDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LEG
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LEG
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LEG
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public LegDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LEG
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoadTimeIsNull() {
            addCriterion("LOAD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLoadTimeIsNotNull() {
            addCriterion("LOAD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLoadTimeEqualTo(Date value) {
            addCriterion("LOAD_TIME =", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeNotEqualTo(Date value) {
            addCriterion("LOAD_TIME <>", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeGreaterThan(Date value) {
            addCriterion("LOAD_TIME >", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LOAD_TIME >=", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeLessThan(Date value) {
            addCriterion("LOAD_TIME <", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeLessThanOrEqualTo(Date value) {
            addCriterion("LOAD_TIME <=", value, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeIn(List<Date> values) {
            addCriterion("LOAD_TIME in", values, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeNotIn(List<Date> values) {
            addCriterion("LOAD_TIME not in", values, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeBetween(Date value1, Date value2) {
            addCriterion("LOAD_TIME between", value1, value2, "loadTime");
            return (Criteria) this;
        }

        public Criteria andLoadTimeNotBetween(Date value1, Date value2) {
            addCriterion("LOAD_TIME not between", value1, value2, "loadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeIsNull() {
            addCriterion("UNLOAD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeIsNotNull() {
            addCriterion("UNLOAD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeEqualTo(Date value) {
            addCriterion("UNLOAD_TIME =", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeNotEqualTo(Date value) {
            addCriterion("UNLOAD_TIME <>", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeGreaterThan(Date value) {
            addCriterion("UNLOAD_TIME >", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UNLOAD_TIME >=", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeLessThan(Date value) {
            addCriterion("UNLOAD_TIME <", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeLessThanOrEqualTo(Date value) {
            addCriterion("UNLOAD_TIME <=", value, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeIn(List<Date> values) {
            addCriterion("UNLOAD_TIME in", values, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeNotIn(List<Date> values) {
            addCriterion("UNLOAD_TIME not in", values, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeBetween(Date value1, Date value2) {
            addCriterion("UNLOAD_TIME between", value1, value2, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andUnloadTimeNotBetween(Date value1, Date value2) {
            addCriterion("UNLOAD_TIME not between", value1, value2, "unloadTime");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdIsNull() {
            addCriterion("load_location_id is null");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdIsNotNull() {
            addCriterion("load_location_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdEqualTo(String value) {
            addCriterion("load_location_id =", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdNotEqualTo(String value) {
            addCriterion("load_location_id <>", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdGreaterThan(String value) {
            addCriterion("load_location_id >", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdGreaterThanOrEqualTo(String value) {
            addCriterion("load_location_id >=", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdLessThan(String value) {
            addCriterion("load_location_id <", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdLessThanOrEqualTo(String value) {
            addCriterion("load_location_id <=", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdLike(String value) {
            addCriterion("load_location_id like", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdNotLike(String value) {
            addCriterion("load_location_id not like", value, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdIn(List<String> values) {
            addCriterion("load_location_id in", values, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdNotIn(List<String> values) {
            addCriterion("load_location_id not in", values, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdBetween(String value1, String value2) {
            addCriterion("load_location_id between", value1, value2, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andLoadLocationIdNotBetween(String value1, String value2) {
            addCriterion("load_location_id not between", value1, value2, "loadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdIsNull() {
            addCriterion("unload_location_id is null");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdIsNotNull() {
            addCriterion("unload_location_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdEqualTo(String value) {
            addCriterion("unload_location_id =", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdNotEqualTo(String value) {
            addCriterion("unload_location_id <>", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdGreaterThan(String value) {
            addCriterion("unload_location_id >", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdGreaterThanOrEqualTo(String value) {
            addCriterion("unload_location_id >=", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdLessThan(String value) {
            addCriterion("unload_location_id <", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdLessThanOrEqualTo(String value) {
            addCriterion("unload_location_id <=", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdLike(String value) {
            addCriterion("unload_location_id like", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdNotLike(String value) {
            addCriterion("unload_location_id not like", value, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdIn(List<String> values) {
            addCriterion("unload_location_id in", values, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdNotIn(List<String> values) {
            addCriterion("unload_location_id not in", values, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdBetween(String value1, String value2) {
            addCriterion("unload_location_id between", value1, value2, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andUnloadLocationIdNotBetween(String value1, String value2) {
            addCriterion("unload_location_id not between", value1, value2, "unloadLocationId");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberIsNull() {
            addCriterion("voyage_number is null");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberIsNotNull() {
            addCriterion("voyage_number is not null");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberEqualTo(String value) {
            addCriterion("voyage_number =", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberNotEqualTo(String value) {
            addCriterion("voyage_number <>", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberGreaterThan(String value) {
            addCriterion("voyage_number >", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberGreaterThanOrEqualTo(String value) {
            addCriterion("voyage_number >=", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberLessThan(String value) {
            addCriterion("voyage_number <", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberLessThanOrEqualTo(String value) {
            addCriterion("voyage_number <=", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberLike(String value) {
            addCriterion("voyage_number like", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberNotLike(String value) {
            addCriterion("voyage_number not like", value, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberIn(List<String> values) {
            addCriterion("voyage_number in", values, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberNotIn(List<String> values) {
            addCriterion("voyage_number not in", values, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberBetween(String value1, String value2) {
            addCriterion("voyage_number between", value1, value2, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andVoyageNumberNotBetween(String value1, String value2) {
            addCriterion("voyage_number not between", value1, value2, "voyageNumber");
            return (Criteria) this;
        }

        public Criteria andCargoIdIsNull() {
            addCriterion("CARGO_ID is null");
            return (Criteria) this;
        }

        public Criteria andCargoIdIsNotNull() {
            addCriterion("CARGO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCargoIdEqualTo(Integer value) {
            addCriterion("CARGO_ID =", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdNotEqualTo(Integer value) {
            addCriterion("CARGO_ID <>", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdGreaterThan(Integer value) {
            addCriterion("CARGO_ID >", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CARGO_ID >=", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdLessThan(Integer value) {
            addCriterion("CARGO_ID <", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdLessThanOrEqualTo(Integer value) {
            addCriterion("CARGO_ID <=", value, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdIn(List<Integer> values) {
            addCriterion("CARGO_ID in", values, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdNotIn(List<Integer> values) {
            addCriterion("CARGO_ID not in", values, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdBetween(Integer value1, Integer value2) {
            addCriterion("CARGO_ID between", value1, value2, "cargoId");
            return (Criteria) this;
        }

        public Criteria andCargoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CARGO_ID not between", value1, value2, "cargoId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LEG
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LEG
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}