package com.rickie.dbsdk.dao;

import com.rickie.dbsdk.model.LegDO;
import com.rickie.dbsdk.model.LegDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LegDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    long countByExample(LegDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int deleteByExample(LegDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int insert(LegDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int insertSelective(LegDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    List<LegDO> selectByExample(LegDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    LegDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LegDO record, @Param("example") LegDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LegDO record, @Param("example") LegDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LegDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LEG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LegDO record);
}