package com.rickie.dbsdk.dao;

import com.rickie.dbsdk.model.LocationDO;
import com.rickie.dbsdk.model.LocationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    long countByExample(LocationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int deleteByExample(LocationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int insert(LocationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int insertSelective(LocationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    List<LocationDO> selectByExample(LocationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    LocationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LocationDO record, @Param("example") LocationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LocationDO record, @Param("example") LocationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LocationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LocationDO record);
}